#pragma once

// Preferences Keys
#ifndef TINYMVCINO_SERVER_PREF_NAMESPACE
  #define TINYMVCINO_SERVER_PREF_NAMESPACE "tinymvcino"
#endif
#ifndef TINYMVCINO_SERVER_FAILED_LOGIN_NUM_PREF_KEY
  #define TINYMVCINO_SERVER_FAILED_LOGIN_NUM_PREF_KEY "failed-login"
#endif
#ifndef TINYMVCINO_SERVER_FAILED_LAST_LOGIN_TIME_PREF_KEY
  #define TINYMVCINO_SERVER_FAILED_LAST_LOGIN_TIME_PREF_KEY "last-f-login"
#endif
#ifndef TINYMVCINO_SERVER_LOGIN_BLOCK_TIME
  #define TINYMVCINO_SERVER_LOGIN_BLOCK_TIME 180000
#endif

// Conf
#ifndef TINYMVCINO_SERVER_PORT
  #define TINYMVCINO_SERVER_PORT 80
#endif

// Auth
#ifndef TINYMVCINO_SERVER_USERNAME_RESOURCE_LABEL
  #define TINYMVCINO_SERVER_USERNAME_RESOURCE_LABEL "username"
#endif
#ifndef TINYMVCINO_SERVER_ACCESS_TOKEN_RESOURCE_LABEL
  #define TINYMVCINO_SERVER_ACCESS_TOKEN_RESOURCE_LABEL "token"
#endif
#ifndef TINYMVCINO_SERVER_EXPIRES_AT_RESOURCE_LABEL
  #define TINYMVCINO_SERVER_EXPIRES_AT_RESOURCE_LABEL "expires_at"
#endif
#ifndef TINYMVCINO_SERVER_DEFAULT_EXPIRES_AT_SECONDS
  #define TINYMVCINO_SERVER_DEFAULT_EXPIRES_AT_SECONDS 600
#endif
#ifndef TINYMVCINO_SERVER_DEFAULT_REFRESH_TOKEN_EXPIRES_SECONDS
  #define TINYMVCINO_SERVER_DEFAULT_REFRESH_TOKEN_EXPIRES_SECONDS 3600
#endif
#ifndef TINYMVCINO_SERVER_TOKEN_CHARS_AVAILABLE
  #define TINYMVCINO_SERVER_TOKEN_CHARS_AVAILABLE "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
#endif
#ifndef TINYMVCINO_SERVER_MAX_TOKEN_LENGTH
  #define TINYMVCINO_SERVER_MAX_TOKEN_LENGTH 65
#endif